// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/tony/Documents/MyApp/umi-dva/src/models/product';

export const models = {
model_1: { namespace: 'product', model: model_1 },
} as const
